name: Quarto Publish (Conda)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Install Miniconda & create your env from environment.yml
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: environment.yml
          activate-environment: bash-presentation

      

      # 3. (Optional) Install any extra npm pkg (reveal-md, etc.)
      - name: Install reveal-md
        run: npm install -g reveal-md

      - name : Set up Quarto CLI
        uses: quarto-dev/quarto-actions/setup@v2

      # 4. Render & deploy
      #    This action will call `quarto render` under the hood
      - name: Quarto Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
